Holidayz/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('homepage.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admins/', include('admins.urls')),
]





handler404 = "dashboard.views.error_404_view"

admins/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.admin_dashboard),
    path('addcountry/', views.add_country),
    path('deletecountry/<int:country_id>', views.delete_country),
    path('addplace/', views.add_place),
    path('showplace/', views.show_place),
    path('showusers/', views.get_users),
    path('showadmins/', views.get_admins),
    path('promote_user/<int:user_id>', views.promote_user),
    path('demote_admin/<int:user_id>', views.demote_admin),
    path('deactivate_admins/<int:user_id>', views.deactivate_admin),
    path('deactivate_user/<int:user_id>', views.deactivate_user),
    path('reactive_admins/<int:user_id>', views.reactive_admin),
    path('reactive_user/<int:user_id>', views.reactive_user),
    path('bookingdata/', views.booking_date),
    path('updateplace/<int:place_id>', views.update_place),
    path('updatecountry/<int:country_id>', views.update_country),
    path('addadmin/', views.add_admin),
    path('update_status/<int:pk>', views.update_status, name='update_status'),
    path('issuedid/', views.issued_id),
    path('contact/', views.contact_form),
    path('logout/', views.logout_view),
]

dashboard/urls.py
from django.urls import path
from . import views
from .views import get_json_offer_data,get_json_model_data
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index_page),
    path('logout/', views.logout_view),
    path('ecard/', views.ecard, name='ecard'),
    path('country/', views.country_list),
    path('profile/', views.profile, name='profile'),
    path('showplaces/', views.show_places),
    path('details/<str:name>', views.place_details, name='details'),
    path('places/<int:c_id>', views.destination_list, name='destination_list'),
    path('watchlist/', views.watchlist, name='watchlist'),
    path('showwatchlist/', views.show_watchlist, name='showwatchlist'),
    path('areyousure/', views.areyou_sure),
    path('booking/<int:place_id>', views.booking),
    path('summary/', views.booking_summary),
    path('password_change', auth_views.PasswordChangeView.as_view(template_name='dashboard/password_change.html')),
    path('password_change_done',
         auth_views.PasswordResetDoneView.as_view(template_name='dashboard/password_change_done.html'),
         name='password_change_done'),
    path('offer_json/', get_json_offer_data, name='offer_json'),
    path('models_json/<str:id>/', get_json_model_data, name='models_json'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admins/models.py
from django.db import models
from django.core import validators
from django.core.validators import *


# Country
class Country(models.Model):
    Name = models.CharField(max_length=120, null=False, validators=[validators.MinLengthValidator(2)],db_index=True)
    Description = models.CharField(max_length=60, validators=[validators.MinLengthValidator(30)])
    Number = models.IntegerField(validators=[validators.integer_validator])
    bg_url = models.URLField(validators=[validators.URLValidator])
    Image = models.ImageField(upload_to="static/uploads/country")

    def __str__(self):
        return self.Name


# Offers included
class Offer(models.Model):
    offer_name = models.CharField(max_length=50, validators=[validators.MinLengthValidator(2)])
    adventure = models.CharField(max_length=100, null=False)
    accommodation = models.CharField(max_length=100, null=False)
    extra = models.TextField(validators=[validators.MaxLengthValidator(250)])

    def __str__(self):
        return self.offer_name


# Places inside country
class Place(models.Model):
    dest_name = models.CharField(max_length=50, validators=[validators.MinLengthValidator(5)],db_index=True)
    dest_type = models.CharField(max_length=50, validators=[validators.MinLengthValidator(3)])
    dest_price = models.IntegerField(validators=[validators.integer_validator])
    dest_desc = models.TextField(validators=[validators.MaxLengthValidator(1000)])
    dest_location = models.CharField(max_length=120)
    dest_image = models.ImageField(upload_to="static/uploads/destination",validators=[validators.URLValidator])
    day_one = models.TextField(validators=[validators.MaxLengthValidator(1000)])
    total_person = models.IntegerField(default=2)
    day_two = models.TextField(validators=[validators.MaxLengthValidator(1000)])
    day_three = models.TextField(validators=[validators.MaxLengthValidator(1000)])
    created_date = models.DateTimeField(auto_now_add=True, null=True)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)

    def __str__(self):
        return self.dest_name

dashboard/models.py
import random

from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.core import validators
from django.core.validators import *

from admins.models import Place, Country, Offer


def random_ecard():
    return str(random.randint(1111111111111111, 9999999999999999))


def random_cvv():
    return str(random.randint(111, 999))


class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    firstname = models.CharField(max_length=50, null=True, validators=[validators.MinLengthValidator(2)])
    lastname = models.CharField(max_length=50, null=True, validators=[validators.MinLengthValidator(2)])
    username = models.CharField(max_length=50)
    email = models.EmailField(unique=True, validators=[validate_email])
    phone = models.CharField(max_length=10, null=True, validators=[validators.MinLengthValidator(7)])
    profile_pic = models.FileField(upload_to='static/uploads/profile', default='static/images/user.png')
    ecard_no = models.CharField(max_length=16, default=random_ecard)
    ecard_cvv = models.CharField(max_length=3, default=random_cvv)
    created_date = models.DateTimeField(auto_now_add=True)


class Watchlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    place = models.ForeignKey(Place, on_delete=models.CASCADE)
    person = models.IntegerField(default=1)


class Booking(models.Model):
    STATUS = (
        ('In-Review', 'In-Review'),
        ('Confirmed', 'Confirmed'),
        ('Denied', 'Denied'),
    )
    place = models.ForeignKey(Place, null=True, on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    offer = models.ForeignKey(Offer, null=True, on_delete=models.CASCADE)
    total_person = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(15)])
    total_price = models.IntegerField(null=True)
    status = models.CharField(max_length=200, choices=STATUS, null=True)
    booked_date = models.DateField()
    created_date = models.DateTimeField(auto_now_add=True)

dashboard/forms.py
from django import forms
from django.contrib.auth.models import User

from django.forms import ModelForm

from . import models
from .models import Profile


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = "__all__"
        exclude = ['user','username','email','ecard_no','ecard_cvv']

dashboard/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from admins.models import Country, Place, Offer
from dashboard.models import Profile, Watchlist, Booking
from homepage.auth import user_only
from .filters import PlaceFilter
from .forms import ProfileForm
from django.http import JsonResponse




# from .filters import CountryFilter


@login_required(login_url='login')
@user_only
def index_page(request):
    context = {
        'activate_home': 'active border-bottom active-class'
    }
    return render(request, 'dashboard/index.html', context)


@login_required(login_url='login')
@user_only
def logout_view(request):
    logout(request)
    return redirect('/')


@login_required(login_url='login')
@user_only
def ecard(request):
    context = {
        'activate_ecard': 'active border-bottom'
    }
    return render(request, 'dashboard/ecard.html', context)


@login_required(login_url='login')
@user_only
def country_list(request):
    data = Country.objects.all().order_by('-id')
    # country_filter = CountryFilter(request.GET, queryset=data)
    context = {
        'data': data,
        'activate_explore': 'active border-bottom active-class',
        # 'country_filter': country_filter
    }
    return render(request, 'dashboard/country.html', context)


@login_required(login_url='login')
@user_only
def profile(request):
    profile = request.user.profile

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Profile has been refined successfully!')
            return redirect('/dashboard/profile')
    context = {
        'form': ProfileForm(instance=profile)
    }
    return render(request, 'dashboard/profile.html', context)


@login_required(login_url='login')
@user_only
def show_places(request):
    place = Place.objects.all().order_by('-id')
    place_filter = PlaceFilter(request.GET,queryset=place)
    place_final = place_filter.qs
    context = {
        'places': place_final,
        'place_filter': place_filter,
        'activate_place': 'active border-bottom active-class h1text'
    }
    return render(request, 'dashboard/showplaces.html', context)


@login_required(login_url='login')
@user_only
def place_details(request, name):
    place = Place.objects.get(dest_name=name)
    context = {
        'details': place,
        'activate_place': 'active'
    }
    return render(request, 'dashboard/details.html', context)


@login_required(login_url='login')
@user_only
def destination_list(request, c_id):
    dests = Country.objects.get(id=c_id)
    print(dests)
    context = {
        'country': dests
    }
    return render(request, 'dashboard/places.html', context)


@login_required(login_url='login')
@user_only
def watchlist(request):
    user = request.user
    place_id = request.GET.get('place_id')
    places = Place.objects.get(id=place_id)
    Watchlist(user=user, place=places).save()
    return redirect('/')


@login_required(login_url='login')
@user_only
def show_watchlist(request):
    watchlist_count = Watchlist.objects.all().count()

    if request.user.is_authenticated:
        user = request.user
        watchlists = Watchlist.objects.filter(user=user)
        return render(request, 'dashboard/watchlist.html',
                      {'watchlist': watchlists, 'count_watchlist': watchlist_count,
                       'activate_watchlist': 'active border-bottom active-class'})


@login_required(login_url='login')
@user_only
def areyou_sure(request):
    return render(request, 'dashboard/sure.html')


@login_required(login_url='login')
@user_only
def booking(request, place_id):
    user = request.user
    place = Place.objects.get(id=place_id)
    place_info = Place.objects.filter(id=place_id)
    offers = Offer.objects.all()

    if request.method == 'POST':
        total_person = request.POST.get('bookin_totalperson')
        booked_date = request.POST.get('bookin_date')
        place_price = place.dest_price
        offer = request.POST.get('bookin_offers')
        total_price = int(total_person) * int(place_price)
        print(total_price)
        bookings = Booking.objects.create(place=place, user=user, offer_id=offer,
                                          total_person=total_person, total_price=total_price,
                                          booked_date=booked_date, status="In-Review")
        if bookings:
            return redirect('/dashboard/summary')
    context = {
        'offers': offers,
        'infos': place_info
    }
    return render(request, 'dashboard/booking.html', context)


def get_json_offer_data(request):
    offer = list(Offer.objects.values())
    return JsonResponse({'data': offer})


def get_json_model_data(request,place_id, *args, **kwargs):
    place = Place.objects.get(id=place_id)
    selected_offer = kwargs.get('id')
    obj_models = list(Offer.objects.filter(id=selected_offer.values()))
    return JsonResponse({'data':obj_models})


@login_required(login_url='login')
@user_only
def booking_summary(request):
    user = request.user
    booking_details = Booking.objects.filter(user=user).order_by('-id')
    context = {
        'bookings': booking_details,
        'activate_booking': 'active border-bottom active-class'
    }

    return render(request, 'dashboard/summary.html', context)


def error_404_view(request, exception):
    return render(request, '404.html')

dashboard/templates/dashboard/booking.html
{% extends 'main_layout.html' %}
{% load static %}

{% block header %}
    <div class="container shadow p-5" style="border-radius: 30px; margin-bottom: 20px">
        <main>
            <div class="py-5 text-center mt-5">
                <h1 style="color: purple;" class="h1text">HolidayZ</h1>
                <h2>Travel Booking Details</h2>
                <p class="lead">Thank God! You are booking your holiday in Nepal!</p>
            </div>
            <form class="form" action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row g-5">
                    <div class="col-md-5 col-lg-4 order-md-last">
                        <h4 class="d-flex justify-content-between align-items-center mb-3">
                            <span class="text-primary">Price Information</span>
                            <span class="badge bg-primary rounded-pill">Unpaid</span>
                        </h4>
                        <ul class="list-group mb-3">
                            {% for price in infos %}
                                <li class="list-group-item d-flex justify-content-between lh-sm">
                                    <div>
                                        <h6 class="my-0">Package Name</h6>
                                        <small class="text-muted">Price Details is Given:</small>
                                    </div>
                                    <span class="text-muted">$ {{ price.dest_price }}</span>
                                </li>
                                <li class="list-group-item d-flex justify-content-between lh-sm">
                                    <div>
                                        <h6 class="my-0">Total Person</h6>
                                        <small class="text-muted">Tourist Counts</small>
                                    </div>
                                    <span class="text-muted">{{ price.total_person }}</span>
                                </li>

                                <li class="list-group-item d-flex justify-content-between">
                                    <span>Total (USD)</span>
                                    <strong>$ {% widthratio price.total_person 1 price.dest_price %}</strong>
                                </li>
                            {% endfor %}
                        </ul>
                        {% for card in infos %}

                            <div class="card text-white bg-primary mb-3 w-100">
                                <div class="card-header">Active Travel Card</div>
                                <div class="card-body">
                                    <h5 class="card-title">Travecl Card: {{ request.user.profile.ecard_no }}</h5>
                                    <p class="card-text">Created Date: {{ request.user.profile.created_date }}</p>
                                    <h3 class="text-right">Discount applied!</h3>
                                </div>
                            </div>


                        {% endfor %}
                    </div>
                    <div class="col-md-7 col-lg-8">

                        <div class="">
                            <h2>Your Choosen Package</h2>
                            <hr/>
                            {% for info in infos %}
                                <div class="card mb-3 shadow border-0" style="width: 100%">
                                    <div class="row g-0">
                                        <div class="col-md-4">
                                            <img src="/{{ info.dest_image }}" class="img-fluid rounded-start"
                                                 alt="...">
                                        </div>
                                        <div class="col-md-8">
                                            <div class="card-body">
                                                <div class="d-flex justify-content-between">
                                                    <h5 class="card-title display-6 fw-bold">{{ info.dest_name }}</h5>
                                                    <button type="button" class="btn btn-primary w-25"
                                                            name="bookin_pricebtn">Price:
                                                        ${{ info.dest_price }}</button>
                                                </div>

                                                <p class="card-text fs-5">{{ info.dest_desc }}</p>
                                                <div class=" text-warning">
                                                    <span class="fa fa-star checked"></span>
                                                    <span class="fa fa-star checked"></span>
                                                    <span class="fa fa-star checked"></span>
                                                    <span class="fa fa-star"></span>
                                                    <span class="fa fa-star"></span>
                                                </div>
                                                <div class="d-flex justify-content-between">
                                                    <p class="card-text fs-2" style="padding-top: 20px;">
                                                        Country: <b>{{ info.country.Name }}</p>
                                                    <button class="btn btn-danger btn-sm w-25 mt-4">
                                                        <i class="fa fa-heart" aria-hidden="true"></i>
                                                        Best deal!
                                                    </button>
                                                </div>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        {% for i in infos %}
                            <h4 class="mb-3">Booking Information</h4>
                            <div class="row g-3">
                                <div class="col-sm-6">
                                    <label for="firstName" class="form-label">First name</label>
                                    <input disabled type="text" class="form-control" id="firstName" placeholder=""
                                           value="{{ request.user.first_name }}" name="bookin_fname"
                                           required>
                                    <div class="invalid-feedback">
                                        Valid first name is required.
                                    </div>
                                </div>

                                <div class="col-sm-6">
                                    <label for="lastName" class="form-label">Last name</label>
                                    <input disabled type="text" class="form-control" id="lastName" placeholder=""
                                           value="{{ request.user.first_name }}" name="bookin_lname"
                                           required>
                                    <div class="invalid-feedback">Valid last name is required.</div>
                                </div>


                                <div class="col-12">
                                    <label for="email" class="form-label">Email </label>
                                    <input type="email" class="form-control" id="email" placeholder="you@example.com"
                                           value="{{ i.user.email }}" name="bookin_email">
                                    <div class="invalid-feedback">Please enter a valid email address</div>
                                </div>

                                <div class="col-12">
                                    <label for="" class="form-label">Pick a date</label>
                                    <label for="birthday"></label><input class="form-control" type="date" id="birthday"
                                                                         name="bookin_date">
                                </div>

                                <div class="col-12">
                                    <label for="" class="form-label">Enter the number of person on your journey</label>
                                    <input type="number" class="form-control" id="email" placeholder="Enter the number"
                                           value="{{ i.total_person }}" name="bookin_totalperson">
                                </div>

                                <div class="col-12">
                                    <label for="bookin_offers" class="form-label">Select your desired package</label>

                                    <select class="form-control w-100" id="bookin_offers" name="bookin_offers">
                                        {% for offer in offers %}
                                            <option value="{{ offer.id }}">Your default selected package: {{ offer.id }}</option>
                                        {% endfor %}
                                    </select>

                                    <select class="form-control w-100" id="bookin_offer" name="bookin_offer">

                                    </select>
                                </div>

                                <div class="col-md-5 w-100">
                                    <label for="address" class="form-label fw-bold">Showing included benefits</label>
                                    <table class="table table-striped">
                                        <thead>
                                        <tr>
                                            <th scope="col">Accomodation</th>
                                            <th scope="col">Adventure</th>
                                            <th scope="col">Extra Package</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <th scope="row">Hotels 3 rooms</th>
                                            <th scope="row">Cycling</th>
                                            <th scope="row">Free Satellite Phone</th>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>

                            <hr class="my-4">


                            <label for="address" class="form-label fw-bold">Add some review about journey
                                (Optional)</label>
                            <textarea class="form-control mb-3" id="Number"
                                      placeholder="Enter details about your journey" value=""
                                      name="bookin_desc"></textarea>

                            <button class="w-100 btn btn-primary" type="submit">Wohoo! Let's Book Your Holiday!</button>

                        {% endfor %}
                    </div>
                </div>
            </form>
        </main>
    </div>
{% endblock header %}
{% block js_file %}
    <script type="text/javascript" src="{% static 'js/offer.js' %}"></script>
{% endblock js_file %}

dashboard/templates/dashboard/country.html
{% extends 'main_layout.html' %}
{% load static %}

{% block header %}
    <section id="featured-box">
        <div class="container my-5">
            <div class="intro">
                <h1 class="display-2 fw-semibold py-4 ">Browse Catalog</h1>
            </div>
            <div class="row">
                {% if data %}
                    {% for country in data %}
                        <div class="col-md-4" onclick="location.href='/dashboard/places/{{ country.id }}'">
                            <div class="country-card"><img src="/{{ country.Image }}" class="img img-responsive">
                                <div class="country-name">{{ country.Name }} <span
                                        class="badge bg-danger">{{ country.Number }} Places</span></div>
                                <div class="desc">{{ country.Description }}</div>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </section>
{% endblock header %}

dashboard/templates/dashboard/ecard.html
{% extends 'main_layout.html' %}
{% load static %}
{% block title %}Travel Card{% endblock title %}

{% block header %}
    <h1 class="text-white">We made you the card</h1>
    <section class="ecard-section">
        <h1 class="text-danger display-3 fw-bold mt-5 ">Travel Card</h1>

        <div class="ecard">
            <div class="face front">
                <h3 class="debit text-dark">HolidayZ Travel Card</h3>
                <h3 class="bank text-dark">Premium</h3>
                <img class="chip" src="{% static 'images/chip.png' %}" alt="chip">
                <h3 class="number text-dark">{{ request.user.profile.ecard_no }}</h3>
                <h5 class="valid text-dark">Valid Until:<span>10/28</span></h5>
                <h5 class="ecard-holder text-dark">{{ request.user.first_name }} {{ request.user.last_name }}</h5>
            </div>
            <div class="face back">
                <div class="blackbar"></div>
                <div class="cvvtext">
                    <div class="white-bar"></div>
                    <div class="cvv">{{ request.user.profile.ecard_cvv }}</div>
                </div>
                <p class="text">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quis ex nec nulla posuere
                    sollicitudin. Proin nec orci at est pellentesque malesuada eu a neque. Maecenas quis porttitor odio.
                    Praesent faucibus dui nisl, ac luctus mauris pulvinar in.
                    Morbi vitae ante a nunc ullamcorper rutrum. Donec non interdum purus, gravida elementum mi.
                </p>
            </div>
        </div>
    </section>

{% endblock %}

dashboard/templates/dashboard/password_change_done.html
{% extends 'main_layout.html' %}
{% load static %}

{% block header %}
    <header id="areyousure">
    <div>
        <h1  class="display-1 fw-bold text-success h1text">Operation Successful</h1>
        <button type="button" class="btn btn-danger btn-lg" onclick="window.location.href='/dashboard/profile'">Redirect to profile</button>
    </div>

    </header>
{% endblock %}

dashboard/templates/dashboard/places.html
{% extends 'main_layout.html' %}
{% load static %}

{% block header %}
    <section id="featured-box">
        <div class="container my-5">
            <div class="intro">
                <h1 class="display-2 fw-semibold py-4 ">Suggested places for you, {{ country.Name }}</h1>
            </div>
            <div class="row row-cols-1 row-cols-md-2 g-4">
                {% if country %}
                    {% for place in country.place_set.all %}
                        <div class="col">
                            <div class="card mb-3" style="max-width: 740px;">
                                <div class="row g-0">
                                    <div class="col-md-4">
                                        <img src="/{{ place.dest_image }}" class="img-fluid rounded-start" alt="..."
                                             style="height: 100%">
                                    </div>
                                    <div class="col-md-8">
                                        <div class="card-body">
                                            <div class="d-flex justify-content-between">
                                                <h5 class="card-title fs-2">{{ place.dest_name }} </h5>
                                                <button type="button" class="btn btn-danger">
                                                    ${{ place.dest_price }}
                                                </button>
                                            </div>

                                            <p class="card-text mt-3">{{ place.dest_desc }}</p>
                                            <div class="d-flex justify-content-between">
                                                <div class="mb-3 text-warning">
                                                    <span class="fa fa-star checked"></span>
                                                    <span class="fa fa-star checked"></span>
                                                    <span class="fa fa-star checked"></span>
                                                    <span class="fa fa-star"></span>
                                                    <span class="fa fa-star"></span>
                                                </div>
                                                <div class="text-success">
                                                   <h5>Region: {{ place.dest_type }}</h5>
                                                </div>

                                            </div>
                                            <div class="d-flex justify-content-between">
                                                <a href="/dashboard/details/{{ place.dest_name }}"><button class="btn btn-primary">Show More Info</button></a>
                                                <h5 class="mt-1"><span class="fa fa-map-marker text-success"></span> {{ place.dest_location }}</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    {% endfor %}
                {% endif %}

            </div>
        </div>
    </section>
{% endblock %}